openapi: 3.0.1
info:
  title: will be replaced
  description: This information will be replaced by the SpringFox config information
  version: 0.0.1
servers:
  - url: /
paths:
  /consultingtypes/basic:
    get:
      tags:
        - consulting-type-controller
      summary: 'Returns a list of all consulting types with basic properties '
      operationId: getBasicConsultingTypeList
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/BasicConsultingTypeListResponseDTO'
        204:
          description: successful operation, but no content
        403:
          description: FORBIDDEN - no/invalid role/authorization or CSRF token
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
  /consultingtypes/{consultingTypeId}/full:
    get:
      tags:
        - consulting-type-controller
      summary: 'Returns the consulting type with all properties for a given consulting type id'
      operationId: getFullConsultingTypeById
      parameters:
        - name: consultingTypeId
          in: path
          description: cnsulting type id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/FullConsultingTypeResponseDTO'
        404:
          description: NOT FOUND - ConsultingType not found
        403:
          description: FORBIDDEN - no/invalid role/authorization or CSRF token
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
  /consultingtypes/byslug/{slug}/full:
    get:
      tags:
        - consulting-type-controller
      summary: 'Returns the consulting type with all properties for a given consulting type slug'
      operationId: getFullConsultingTypeBySlug
      parameters:
        - name: slug
          in: path
          description: cnsulting type slug
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/FullConsultingTypeResponseDTO'
        404:
          description: NOT FOUND - ConsultingType not found
        403:
          description: FORBIDDEN - no/invalid role/authorization or CSRF token
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition

components:
  schemas:

    BasicConsultingTypeListResponseDTO:
      type: array
      items:
        $ref: '#/components/schemas/BasicConsultingTypeResponseDTO'

    BasicConsultingTypeResponseDTO:
      type: object
      properties:
        id:
          type: integer
          example: 100
        titles:
          allOf:
            - $ref: '#/components/schemas/ConsultingTypeTitlesDTO'
        isSubsequentAdditionAllowed:
          type: boolean
          example: true

    FullConsultingTypeResponseDTO:
      type: object
      properties:
        id:
          type: integer
          example: 100
        titles:
          allOf:
            - $ref: '#/components/schemas/ConsultingTypeTitlesDTO'
        isSubsequentAdditionAllowed:
          type: boolean
          example: true

    ConsultingTypeTitlesDTO:
      type: object
      properties:
        default:
          type: string
          example: Beratung xyz
        short:
          type: string
          example: xyz
        long:
          type: string
          example: Beratung xyz in Ort
        welcome:
          type: string
          example: Herzlich Willkommen zu Beratung xyz
        registrationDropdown:
          type: string
          example: Beratung xyz
